version: '3.9'

networks:
  network_iot:
    external:
      name: iot-net

services:
  www:
    container_name: keddy-voice
    build: .
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=keddy.love, www.keddy.love
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=keddy.love, www.keddy.love
      - LETSENCRYPT_EMAIL=jcanahuirev@gmail.com
    networks:
      - network_iot